###
POST http://localhost:3000/purchases HTTP/1.1
Content-Type: 'application/json'
 
 {
    "_id": "5ce1a0e9a75a287818d31136", 
    "userId": "5ce1a0e9a75a287818d31136",
    "name": "Shoes_Jordan23",
    "category": "Staff",
    "price": "100",
    "isAvailable": "true",
    "image": "img.png",
    "description": "good shoes",
    "date": "new Date()",
    "status": "pending"
 }

###

POST http://localhost:3000/purchases HTTP/1.1
 
Content-Type: application/json

 {
   "userId" : "5ce1a0e9a75a287818d31136"
}

###
 PUT http://localhost:3000/purchases HTTP/1.1
 Content-Type: 'application/json'

 {
    "userId": "5ce1a0e9a75a287818d31136",
    "_id": "5ce1a0e9a75a287818d31136", 
    "name": "Shoes_Jordan23",
    "category": "Staff",
    "price": "100",
    "isAvailable": "true",
    "image": "img.png",
    "description": "good shoes",
    "date": "new Date()",
    "status": "pending"
 }

###
 GET http://localhost:3000/purchases HTTP/1.1

###
Content-Type: application/json
POST http://localhost:3000/sells HTTP/1.1

content
{
   "salesId" : "5ce1a0dda75a287818d31135",
    "userId": "5ce19f7731ad210ee85509a6",
    "customerId": "5ce19f7731ad210ee85509a6",
    "productId": "5ce1a0dda75a287818d31135",
    "name": "Samsung",
    "category": "electronics",
    "price": "250.6",
    "isAvailable": "true",
    "image": ["img.png"],
    "description": "In good condition",
    "status": "Delivered",
    "firstName": "Hilina",
    "lastName": "Beyene",
    "Phone": "5153464893",
    "email": "test@gmail.com",
    "street": "1000 4th N",
    "city": "Fairfield",
    "state": "Iowa",
    "zip": "57552",
    "payment":"paypal"
}
cart
{
	
    "userId": "5ce19f7731ad210ee85509a6",
    "productId": "5ce1a0dda75a287818d31135",
    "name": "test",
    "category": "ele",
    "price": "26.4",
    "isAvailable": "true",
    "image": "[img.png]",
    "description": "good"
 }