###
POST http://localhost:3000/purchases HTTP/1.1
Content-Type: 'application/json'
 
 {
    "_id": "5ce1a0e9a75a287818d31136", 
    "userId": "5ce1a0e9a75a287818d31136",
    "name": "Shoes_Jordan23",
    "category": "Staff",
    "price": "100",
    "isAvailable": "true",
    "image": "img.png",
    "description": "good shoes",
    "date": "new Date()",
    "status": "pending"
 }

###
 PUT http://localhost:3000/purchases HTTP/1.1
 Content-Type: 'application/json'

 {
    "_id": "5ce1a0e9a75a287818d31136", 
    "userId": "5ce1a0e9a75a287818d31136",
    "name": "Shoes_Jordan23",
    "category": "Staff",
    "price": "100",
    "isAvailable": "true",
    "image": "img.png",
    "description": "good shoes",
    "date": "new Date()",
    "status": "pending"
 }

###
 GET http://localhost:3000/purchases HTTP/1.1

