###

POST http://localhost:3000/users/signup HTTP/1.1
Content-Type: application/json

{
    "firstname":"Asaad",
    "lastname":"Saad",
    "username":"asaad",
    "phone":"3454546593",
    "email":"asaad@mum.edu",
    "password":"potato"
}


###
GET http://localhost:3000/products/user/5ce1d78ada829c197d9a5a69 HTTP/1.1


###
POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
    "email":"asaad@mum.edu",
    "password":"potato"
}

###

http://localhost:3000/products

###

PUT http://localhost:3000/users/update/address HTTP/1.1
Content-Type: application/json

{
   "data":{
     "street":"1000N 4th",
    "zipcode":"52557",
    "city":"Fairfield",
    "state":"iowa"
   }
}